### ISSUE TITLE
[Bug] Creating multiple child element after editing using RTE

### ISSUE THREAD

**Issue by mudit-mittal** [artf/grapesjs#1495]
Hi All,

I am  getting below issues which are related to RTE

1) RTE creating multiple child's as action performed on text block. Ex:- suppose we performed same action (Bold) three times in sequence on same text block then its creating three child's on the same element.
2) Font action in RTE is only supporting font size values between 1 to 7.

![image](https://user-images.githubusercontent.com/44024159/46732930-7ee24780-ccac-11e8-80e3-6e1092d162dd.png)

Kindly revert on priority. Thanks in Advance !!!

**Comment by mararn1618** [comment]
Hi mudit-mittal,

this is somewhat fixed in 0.14.33 and the same as
 - #761
 - #1484

**Comment by mudit-mittal** [comment]
I am using latest version of library but issue is still here so kindly review.
