### ISSUE TITLE
Cannot load javascript under grapesjs

### ISSUE THREAD

**Issue by henry930** [artf/grapesjs#3195]
Can javascript under the grapesjs panel load?

**Comment by Swindler36** [comment]
Hi @henry930,

I fixed this problem by developing an reloader.
```js
let editorConfig = {
// your configs
}
let editor = false;

function editorLoad(){
  $(editorConfig.container).empty(); // with JQuery
  editor = grapesjs.init(editorConfig);
  editor.load();
}

editorLoad();
```

If you want to update your config,
```js
// for example
/* 
old
editorConfig.height = '100px'
*/
editorConfig.height = '150px';
editorLoad();
``` 
Your editor will reload. Your html, css... will remain.

**Comment by artf** [comment]
https://grapesjs.com/docs/modules/Components-js.html

**Comment by Aze1337** [comment]
i dont understand how in 4 years it still does not supports importing single html file that renders with javascript ? most styling are very off
