### ISSUE TITLE
image upload with cross Origin issue 

### ISSUE THREAD

**Issue by vtista** [artf/grapesjs#416]
I have checked all the issues history,but didin't find a way out.
![default](https://user-images.githubusercontent.com/22438077/31529039-3c5a130e-b009-11e7-8db9-6a2eb600f337.png)
i changed here to allow fetch to cross origin access.
my asset manager is fine
![default](https://user-images.githubusercontent.com/22438077/31529078-846a613a-b009-11e7-95b0-c4f04914113e.png)
and here is my php code
![default](https://user-images.githubusercontent.com/22438077/31529089-9900c09e-b009-11e7-9c09-734e7ba85282.png)
also file uploaded successed
![default](https://user-images.githubusercontent.com/22438077/31529160-26994b38-b00a-11e7-994f-fd44ab306c9d.png)

but it shows me those errors
![default](https://user-images.githubusercontent.com/22438077/31529127-e8b6221e-b009-11e7-8d0f-af14ad91736b.png)
and this is my console log
![default](https://user-images.githubusercontent.com/22438077/31529147-0d995f6a-b00a-11e7-9a93-b525976f0e51.png)

**Comment by mekamleshk** [comment]
Hi @vtista 

The response from your php code should be like this :

`[{"type":"image","src":"localhost/test/img/wechat.jpg","height":"350","weight":"250"}],`

Trying removing the slashes like this :

`echo json_encode($response,JSON_UNESCAPED_SLASHES);`

For more reference you can check my code [Here](https://github.com/artf/grapesjs/issues/393)

**Comment by vtista** [comment]
@mekamleshk Thanks a lot,i just did as you said,but the issue was still there
![default](https://user-images.githubusercontent.com/22438077/31533328-3fbe2e16-b024-11e7-80f4-5fd8f6b2594f.png)

![default](https://user-images.githubusercontent.com/22438077/31533250-0cde24a6-b024-11e7-87da-19904401352e.png)
![default](https://user-images.githubusercontent.com/22438077/31533275-2323fdda-b024-11e7-82d9-8f8b2005384d.png)
do you have any idea? :)

**Comment by mekamleshk** [comment]
@vtista were you able to upload the file ?

Not sure about the error you are get, I can suggest you to go to your project folder and try this command:
`npm i`

**Comment by artf** [comment]
@mekamleshk 
> The response from your php code should be like this :
`[{"type":"image","src":"localhost/test/img/wechat.jpg","height":"350","weight":"250"}],`


Nope, `{ data: [...` is a correct format

@vtista seems like the same as #372 which has been fixed. Are sure to use the latest version?

**Comment by vtista** [comment]
I followed #372 also used latest version,but problem still there,do you think the problem cause i used it in cross domian ?@artf
https://user-images.githubusercontent.com/22438077/31529039-3c5a130e-b009-11e7-8db9-6a2eb600f337.png

**Comment by artf** [comment]
If you had problems with CORS you wouldn't be able to see the response. 
Anyway, try to add this listener and see what you get
```js
editor.on('asset:upload:response', jsonRes => console.log('You should see a json: ', jsonRes))
```
Are you sure you haven't disabled `autoAdd` in `assetManager` config?

**Comment by mekamleshk** [comment]
@vtista 

After uploading the files to the server, I'm returning the lastest uploaded file in the response which is working perfectly now,

`$dir = 'uploads/';
		        $lastMod = 0;
				$lastModFile = '';
				foreach (scandir($dir) as $entry) {
				    if (is_file($dir.$entry) && filectime($dir.$entry) > $lastMod) {
				        $lastMod = filectime($dir.$entry);
				        $lastModFile = $entry;
				    }
				}
			        
				$images[] = array('type' => 'image',
               				 'src' => 'http://cimailer.dev/uploads/'.basename($lastModFile),
               				 'height' => '350',
               				 'weight' => '250'
               				);
				
	        	if(!empty($images))
	            {
	            	$data = array('data' => $images);          	
	            }
	            
	            if(!empty($data))
	            {
	            	echo json_encode($data,JSON_UNESCAPED_SLASHES);	
	            }`

**Comment by vtista** [comment]
hey,guys sorry to reply this late.I got another project of our company need to update in hurry last week.Anyway,the solution you guys provided works fine after i moved the files in same domain.But if you guys have time please take a look at how we can upload images in cross domain condition.Thanks in advanced! 👍
