### ISSUE TITLE
[BUG]: HTML attributes/traits not escaped

### ISSUE THREAD

**Issue by nojacko** [artf/grapesjs#912]
When double quotes are added to an attribute it breaks the HTML.

1. https://jsfiddle.net/szLp8h4n/
1. Drag in the link block.
1. Click the link in the editor
1. Go to "Component settings" panel
1. Enter `This is an  "example"` into `title` field.
1. Click the view code icon.
1. Invalid HTML is generated
```html
<div class="c318">Hello World!!!</div>
<a title="This is an  "example"" class="c739">Link</a>
```

**Comment by artf** [comment]
Thanks for the catch James
PRs are welcome

**Comment by artf** [comment]
Fixed by https://github.com/artf/grapesjs/pull/939

**Comment by nojacko** [comment]
Looks like the fix only replaces the code in the Grapes editor but when getHtml() is called the issue is still present.

Inspected code:  
```<input type="text" name="company" placeholder="This is an &quot;example&quot;" required="false" data-highlightable="1" class="gjs-comp-selected">```

Output from get `editor.getHtml()`: 
```<input type="text" name="company" placeholder="This is an "example"" required="false"/>```

**Comment by artf** [comment]
@nojacko I don't build files before the release so if you're using files from `dist` you're still using the old one
